[package]
name = "xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# Workspace
anyhow.workspace = true
async-openai = "0.14.3"
bencher_json = { workspace = true, features = ["lite"] }
camino.workspace = true
clap.workspace = true
reqwest = { workspace = true, features = ["default"] }
serde_json.workspace = true
serde_urlencoded.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
url.workspace = true
