[package]
name = "xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# Workspace
anyhow.workspace = true
bencher_json = { workspace = true, features = ["lite"] }
camino.workspace = true
clap.workspace = true
reqwest = { workspace = true, features = ["default"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
