[alias]
xtask = "run --manifest-path ./xtask/Cargo.toml --"

[target.'cfg(all())']
rustflags = [
    # https://github.com/rust-lang/rust-clippy
    "-Wclippy::all",
    # cargo
    "-Wclippy::cargo",
    "-Aclippy::cargo_common_metadata",   # Checks to see if all common metadata is defined in Cargo.toml.
    "-Aclippy::multiple_crate_versions", # Checks to see if multiple versions of a crate are being used.
    # pedantic
    "-Wclippy::pedantic",
    "-Aclippy::missing_errors_doc",      # Checks the doc comments of publicly visible functions that return a Result type and warns if there is no # Errors section.
    "-Aclippy::missing_panics_doc",      # Checks the doc comments of publicly visible functions that may panic and warns if there is no # Panics section.
    "-Aclippy::module_name_repetitions", # Detects type names that are prefixed or suffixed by the containing module’s name.
    "-Aclippy::must_use_candidate",      # Checks for public functions that have no #[must_use] attribute, but return something not already marked must-use, have no mutable arg and mutate no statics.
    # restriction
    # "-Wclippy::restriction",
    # "-Wclippy::arithmetic_side_effects", # Checks any kind of arithmetic operation of any type.
    "-Wclippy::as_underscore", # Checks for the usage of as _ conversion using inferred type.
    "-Wclippy::dbg_macro",     # Checks for usage of the dbg! macro.
    "-Wclippy::print_stdout",  # Checks for printing on stdout. The purpose of this lint is to catch debugging remnants.
    "-Wclippy::print_stderr",  # Checks for printing on stderr. The purpose of this lint is to catch debugging remnants.
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/mold"]
